export default {
  SET_AUTH: 'SET_AUTH',
  GET_AUTH: 'GET_AUTH',
  SET_SITE: 'SET_SITE',
  GO_LOGIN: 'GO_LOGIN',

  SET_LOCALE: 'SET_LOCALE',
  FETCH_LOCALE: 'FETCH_LOCALE',
  
  FETCH_SITE: 'FETCH_SITE',
  DOWNLOAD: 'DOWNLOAD',

}